### PR TITLE
Added in missing zend framework components

### PR DESCRIPTION
**Pull request by settermjd**
I attempted to use the package as-is and encountered a series of missing class exceptions. So after working through each of them, I've added them to composer.json so that the package works "out of the box".

### CODE REVIEW

**Comment by Ocramius** [comment]
Hmm, this module usually works in a ZendSkeletonApplication context.

The change seems fine to me, but we don't directly depend on any of these components, so I think the issue should probably be raised on `zendframework/zend-mvc`. @BinaryKitten thoughts?

**Comment by BinaryKitten** [comment]
@settermjd - any chance you'd be willing to discuss this in IRC etc? might be i need to update the documentation for getting started.

**Comment by settermjd** [comment]
Thanks for the chat on IRC. I only just saw the email notification now :-(

**Comment by settermjd** [comment]
Is this going ahead?

**Comment by BinaryKitten** [comment]
Thanks for this @settermjd - seems that the MVC no longer requires the parts, so ZeffMu needs them.

Merged

**Comment by settermjd** [comment]
Awesome. Happy to help out.

**Pull request merged**
